name: place_picker_google
description: "A place picker package for google maps api fully written in dart for Flutter."
version: 0.0.6
homepage: https://github.com/joafc96/place_picker_google
repository: https://github.com/joafc96/place_picker_google
issue_tracker: https://github.com/joafc96/place_picker_google/issues
documentation: https://github.com/joafc96/place_picker_google/blob/main/README.md

topics:
  - map-picker
  - location-picker
  - flutter-location-picker
  - google-maps-flutter
  - place-picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  uuid: ^3.0.7
  geolocator: ^9.0.2
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true