name: place_picker_google
description: "A place picker package for google maps api fully written in dart for Flutter."
homepage: https://github.com/joafc96/place_picker_google
repository: https://github.com/joafc96/place_picker_google
issue_tracker: https://github.com/joafc96/place_picker_google/issues
documentation: https://github.com/joafc96/place_picker_google/blob/main/README.md
version: 0.0.16

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  google_maps_flutter: ^2.11.0
  geolocator: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

topics:
  - map-picker
  - location-picker
  - flutter-location-picker
  - google-maps-flutter
  - place-picker